import React, { useState, useEffect, use } from 'react'
import { bestTestimonials } from '@/constants/besttestimonials'

import styles from '@/styles/sidepaneltest.module.css'


const testimonials = bestTestimonials;
const createRandomNum = Math.floor((Math.random() * testimonials.length));
let testimony = testimonials[createRandomNum];


const SidepanelTest = ({ text, course }) => {

  const [test, setTest] = useState(testimony)

  useEffect(() => {
    console.log(test)
  }, [test])

  return (
    <div className={styles.sidepanel__container}>
      <div className={styles.sidepanel__container_text}>"{test.text}"</div>
      <div className={styles.sidepanel__container_course}>{test.course}</div>
    </div>
  )
}

export default SidepanelTest








//having promise error.  need to fetch data immediately when this component loads (onInit or useEffect?)
  //useEffect a function that fetches the data for the best array items, then the create random number function runs, then using that random number, display the selected testimonial item



//   const randomTestimonial = () => {
//     return testimonials[createRandomNum];
// }
// useEffect(() => {
//   setTest(testimonials[createRandomNum]);
// })


// getting hydration error.  Likely need to do some async
  
  //useEffect Hook


  //setTimeout(() =>)

  // replace testimonials value with best quotes array (make best quotes array)

  // useEffect(() => {

  //   }
  // )


  

  // set use state initial value to what is generated by the random number generator
  // const [num, setNum] = useState(createRandomNum);


  // create a function that calls createRandomNum every 4 seconds
  