import React, { useState } from 'react'
import { DurhamUniversityData, UncGreensboroData, UncChapelHillData } from '@/constants/testimonials'

import styles from '@/styles/sidepaneltest.module.css'


//may need to put logic in parent??


const SidepanelTest = ({ text, course }) => {
  

  // replace testimonials value with best quotes array (make best quotes array)
  const testimonials = DurhamUniversityData;

  const createRandomNum = Math.floor((Math.random() * testimonials.length));

  // set use state initial value to what is generated by the random number generator
  // const [num, setNum] = useState(createRandomNum);



  // console.log(testimonials);

  // create a function that calls createRandomNum every 4 seconds
  


  return (
    <div className={styles.sidepanel__container}>
      <p className={styles.sidepanel__container_text}>{testimonials[createRandomNum].text}</p>
      <p className={styles.sidepanel__container_course}>{testimonials[createRandomNum].course}</p>
    </div>
  )
}

export default SidepanelTest
